#!/bin/bash
xdg-open https://pages.pedf.cuni.cz/studovna/wp-admin/admin.php?page=booked-settings#export-appointments
rm ~/Stažené/booked_appointments_export.csv
echo Stáhni CSV soubor a spusť příkaz tymovka-print
